version: '3.7'
services:
  api:
    build: .
    image: businesses-api
    networks:
    - mysql-net
    depends_on:
    - mysql
    ports:
      - 8000:8000
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    links:
    - "mysql:api"

  mysql:
    image: mysql:5
    networks:
    - mysql-net
    volumes:
      - bar-volume:/var/lib/mysql
      - ./db-init:/00-db-init.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
    bar-volume: {}
networks:
    mysql-net:
      driver: bridge
